# Generated by Django 5.1.2 on 2026-01-06 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_course_about_blurb_and_more'),
        ('quicktest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickTestDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quicktest_definition', to='courses.module')),
            ],
        ),
        migrations.CreateModel(
            name='QuickTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quicktest.quicktestdefinition')),
            ],
        ),
    ]
