# Generated by Django 5.1.2 on 2026-03-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicktest', '0002_quicktestdefinition_quicktestquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicktestquestion',
            name='expected_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='quicktestquestion',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Selección múltiple'), ('text', 'Respuesta escrita'), ('signature', 'Firma por nombre completo')], default='mcq', max_length=16),
        ),
        migrations.AlterField(
            model_name='quicktestquestion',
            name='correct_option',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='quicktestquestion',
            name='option_a',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='quicktestquestion',
            name='option_b',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='quicktestquestion',
            name='option_c',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='quicktestquestion',
            name='option_d',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
