# Generated by Django 5.1.2 on 2026-03-10 04:42

from django.db import migrations, models


def backfill_question_order(apps, schema_editor):
    QuickTestQuestion = apps.get_model("quicktest", "QuickTestQuestion")
    definition_ids = (
        QuickTestQuestion.objects.values_list("definition_id", flat=True).distinct()
    )
    for definition_id in definition_ids:
        qs = QuickTestQuestion.objects.filter(definition_id=definition_id).order_by("id")
        for idx, question in enumerate(qs):
            question.order = idx
            question.save(update_fields=["order"])


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('quicktest', '0003_quicktestquestion_expected_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quicktestquestion',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='quicktestquestion',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(backfill_question_order, migrations.RunPython.noop),
    ]
