# Generated by Django 5.1.2 on 2026-01-06 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_alter_address_user'),
        ('enrollments', '0004_stripeevent_remove_becaapplication_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='becaapplication',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beca_applications', to='address.address'),
        ),
    ]
