# Generated by Django 5.1.2 on 2026-03-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0005_alter_becaapplication_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'En revisión (Beca)'), ('pending_payment', 'Esperando pago'), ('active', 'Activo'), ('completed', 'Completado'), ('rejected', 'Beca rechazada'), ('cancelled', 'Cancelado por usuario')], default='active', max_length=32),
        ),
    ]
