# Generated by Django 5.1.2 on 2024-10-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imagen',
            field=models.ImageField(default='profiles/default.jpg', upload_to='Profile/'),
        ),
    ]
