# Generated by Django 5.1.2 on 2025-11-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_rename_title_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='forcarousel',
            field=models.BooleanField(default=True, verbose_name='Carousel'),
        ),
    ]
