# Generated by Django 5.1.2 on 2024-10-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_column_pagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='excerpt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
