# Generated by Django 5.1.2 on 2024-10-29 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_pagecontent_excerpt'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='habilidades/')),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='page.pageimg')),
            ],
        ),
    ]
