# Generated by Django 5.1.2 on 2024-10-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='icon',
            field=models.ImageField(blank=True, help_text='Ícono para la página principal.', null=True, upload_to='metadata/icons/'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='search_image',
            field=models.ImageField(blank=True, help_text='Imagen para mostrar en los resultados de búsqueda.', null=True, upload_to='metadata/search_images/'),
        ),
    ]
