# Generated by Django 5.1.2 on 2025-12-28 05:18

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_description_alter_lesson_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='about_blurb',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='course about'),
        ),
        migrations.AddField(
            model_name='course',
            name='manual_certified_add',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='show_on_about',
            field=models.BooleanField(default=False),
        ),
    ]
