# Generated by GitHub Copilot

from django.db import migrations


def seed_taod(apps, schema_editor):
    Program = apps.get_model('courses', 'Program')
    Program.objects.get_or_create(name='TAOD')


def unseed_taod(apps, schema_editor):
    Program = apps.get_model('courses', 'Program')
    Program.objects.filter(name='TAOD').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_program_course_program_programyearstat'),
    ]

    operations = [
        migrations.RunPython(seed_taod, reverse_code=unseed_taod),
    ]
