# Generated by Django 5.1.2 on 2025-12-28 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_seed_taod_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='about_blurb',
        ),
        migrations.RemoveField(
            model_name='course',
            name='show_on_about',
        ),
    ]
