# Generated by Django 5.1.2 on 2026-01-06 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_course_about_blurb_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quicktestresult',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='quicktestresult',
            name='module',
        ),
        migrations.RemoveField(
            model_name='quicktestresult',
            name='user',
        ),
        migrations.RemoveField(
            model_name='test',
            name='module',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuickTestResult',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
