# Generated by Django 5.1.2 on 2026-02-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_quicktestresult_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='payment_required',
            field=models.BooleanField(default=False),
        ),
    ]
