# Generated by Django 5.1.2 on 2026-03-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_lesson_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='study_material',
            field=models.FileField(blank=True, null=True, upload_to='course_materials/'),
        ),
    ]
