# Generated by Django 5.1.2 on 2026-03-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_study_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='study_material_drive_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
