# Generated by Django 5.1.2 on 2025-11-16 18:03

import classroom.certifications.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
        ('courses', '0002_quicktestresult_delete_testresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-issued_date']},
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='uuid',
            new_name='public_uuid',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='enrollment',
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_number',
            field=models.CharField(default='TEMP-CERT', max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issued_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='certificate',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=classroom.certifications.models.certificate_upload_to),
        ),
        migrations.AddField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL),
        ),
    ]
