# Generated by Django 5.1.2 on 2025-12-28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0002_alter_certificate_options_and_more'),
        ('courses', '0002_quicktestresult_delete_testresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InPersonCertificateIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('district', models.CharField(max_length=120)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_person_issues', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_person_certificate_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_date', 'course__title', 'district'],
                'unique_together': {('course', 'issued_date', 'district')},
            },
        ),
    ]
