# Generated by Django 5.1.2 on 2026-01-13 12:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0002_add_uuid_to_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
