# Generated by Django 5.1.2 on 2025-12-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0003_inpersoncertificateissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpersoncertificateissue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/in_person/'),
        ),
    ]
