# Generated by Django 5.1.2 on 2025-12-28 17:57

import classroom.certifications.models
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0004_inpersoncertificateissue_image'),
        ('courses', '0007_seed_taod_program'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inpersoncertificateissue',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='inpersoncertificateissue',
            name='district',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='inpersoncertificateissue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=classroom.certifications.models.in_person_issue_image_upload_to),
        ),
        migrations.AlterField(
            model_name='inpersoncertificateissue',
            name='issued_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='inpersoncertificateissue',
            constraint=models.UniqueConstraint(fields=('course', 'issued_date', 'district'), name='uniq_inperson_course_date_district'),
        ),
    ]
