# Generated by Codex on 2026-02-15

import uuid
from django.db import migrations, models


def ensure_public_uuid_column(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    cursor = schema_editor.connection.cursor()

    if vendor == "postgresql":
        cursor.execute(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'certifications_certificate'
                      AND column_name = 'public_uuid'
                ) THEN
                    ALTER TABLE certifications_certificate
                    ADD COLUMN public_uuid uuid;
                END IF;
            END$$;
            """
        )
    else:
        cursor.execute("PRAGMA table_info('certifications_certificate');")
        columns = [row[1] for row in cursor.fetchall()]
        if "public_uuid" not in columns:
            cursor.execute("ALTER TABLE certifications_certificate ADD COLUMN public_uuid text;")


def backfill_public_uuid(apps, schema_editor):
    Certificate = apps.get_model("certifications", "Certificate")
    batch = []
    for cert in Certificate.objects.filter(public_uuid__isnull=True).iterator(chunk_size=500):
        # Prefer existing uuid if present, else generate a new one
        cert.public_uuid = cert.uuid or uuid.uuid4()
        batch.append(cert)
        if len(batch) >= 500:
            Certificate.objects.bulk_update(batch, ["public_uuid"])
            batch.clear()
    if batch:
        Certificate.objects.bulk_update(batch, ["public_uuid"])


def ensure_public_uuid_constraints(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    cursor = schema_editor.connection.cursor()

    if vendor == "postgresql":
        cursor.execute(
            """
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'certifications_certificate'
                      AND column_name = 'public_uuid'
                ) THEN
                    ALTER TABLE certifications_certificate
                    ALTER COLUMN public_uuid SET NOT NULL;
                END IF;
            END$$;
            """
        )
        cursor.execute(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'certifications_certificate_public_uuid_key'
                ) THEN
                    ALTER TABLE certifications_certificate
                    ADD CONSTRAINT certifications_certificate_public_uuid_key UNIQUE(public_uuid);
                END IF;
            END$$;
            """
        )
    else:
        cursor.execute(
            "CREATE UNIQUE INDEX IF NOT EXISTS certs_cert_public_uuid_uniq ON certifications_certificate(public_uuid);"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("certifications", "0004_add_cert_no_if_missing"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="certificate",
                    name="public_uuid",
                    field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False, db_index=True),
                )
            ],
        ),
        migrations.RunPython(ensure_public_uuid_column, migrations.RunPython.noop),
        migrations.RunPython(backfill_public_uuid, migrations.RunPython.noop),
        migrations.RunPython(ensure_public_uuid_constraints, migrations.RunPython.noop),
    ]
