# Generated by Django 5.1.2 on 2025-12-28 18:54

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0005_alter_inpersoncertificateissue_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpersoncertificateissue',
            name='impact',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inpersoncertificateissue',
            name='in_person_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inpersoncertificateissue',
            name='note',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=255),
        ),
    ]
