# Generated by Codex on 2026-02-15

from django.db import migrations, models
from django.utils import timezone


def ensure_created_at_column(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    cursor = schema_editor.connection.cursor()

    if vendor == "postgresql":
        cursor.execute(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'certifications_certificate'
                      AND column_name = 'created_at'
                ) THEN
                    ALTER TABLE certifications_certificate
                    ADD COLUMN created_at timestamp with time zone;
                END IF;
            END$$;
            """
        )
    else:
        cursor.execute("PRAGMA table_info('certifications_certificate');")
        columns = [row[1] for row in cursor.fetchall()]
        if "created_at" not in columns:
            cursor.execute("ALTER TABLE certifications_certificate ADD COLUMN created_at datetime;")


def backfill_created_at(apps, schema_editor):
    Certificate = apps.get_model("certifications", "Certificate")
    now = timezone.now()
    Certificate.objects.filter(created_at__isnull=True).update(created_at=now)


class Migration(migrations.Migration):
    dependencies = [
        ("certifications", "0005_add_public_uuid"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="certificate",
                    name="created_at",
                    field=models.DateTimeField(default=timezone.now, db_index=True),
                )
            ],
        ),
        migrations.RunPython(ensure_created_at_column, migrations.RunPython.noop),
        migrations.RunPython(backfill_created_at, migrations.RunPython.noop),
    ]
