# Generated by Django 5.1.2 on 2026-01-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0006_inpersoncertificateissue_impact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InPersonCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
    ]
