# Generated by Codex on 2026-02-15

from django.db import migrations, models


def ensure_certificate_number_column(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    cursor = schema_editor.connection.cursor()

    if vendor == "postgresql":
        cursor.execute(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'certifications_certificate'
                      AND column_name = 'certificate_number'
                ) THEN
                    ALTER TABLE certifications_certificate
                    ADD COLUMN certificate_number varchar(30);
                END IF;
            END$$;
            """
        )
    else:
        cursor.execute("PRAGMA table_info('certifications_certificate');")
        columns = [row[1] for row in cursor.fetchall()]
        if "certificate_number" not in columns:
            cursor.execute("ALTER TABLE certifications_certificate ADD COLUMN certificate_number varchar(30);")


def backfill_certificate_number(apps, schema_editor):
    Certificate = apps.get_model("certifications", "Certificate")
    for cert in Certificate.objects.filter(certificate_number__isnull=True).only("id", "cert_no"):
        Certificate.objects.filter(id=cert.id).update(certificate_number=cert.cert_no)


class Migration(migrations.Migration):
    dependencies = [
        ("certifications", "0006_add_created_at"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="certificate",
                    name="certificate_number",
                    field=models.CharField(max_length=30, unique=True, blank=True, editable=False),
                )
            ],
        ),
        migrations.RunPython(ensure_certificate_number_column, migrations.RunPython.noop),
        migrations.RunPython(backfill_certificate_number, migrations.RunPython.noop),
    ]
