# Generated by Codex on 2026-02-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certifications", "0007_add_certificate_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="pending",
            field=models.BooleanField(default=False, db_index=True),
        ),
    ]
