# Generated by Django 5.1.2 on 2026-01-04 03:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0008_inpersoncertificateissue_category'),
        ('courses', '0008_remove_course_about_blurb_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inpersoncertificateissue',
            name='uniq_inperson_course_date_district',
        ),
        migrations.AddConstraint(
            model_name='inpersoncertificateissue',
            constraint=models.UniqueConstraint(fields=('course', 'issued_date', 'district', 'category'), name='uniq_inperson_course_date_district'),
        ),
    ]
