# Generated by Django 5.1.2 on 2026-03-10 05:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0008_add_pending'),
        ('courses', '0013_course_study_material_drive_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BecadoCertificateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=180)),
                ('educational_center', models.CharField(max_length=200)),
                ('regional', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('authorized', 'Autorizado')], db_index=True, default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('authorized_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_becado_certificate_requests', to=settings.AUTH_USER_MODEL)),
                ('certificate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='becado_request', to='certifications.certificate')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='becado_certificate_requests', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='becado_certificate_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-sent_at',),
            },
        ),
    ]
