# Generated by Django 5.1.2 on 2026-05-20 17:23

import classroom.certifications.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0009_becadocertificaterequest'),
        ('courses', '0013_course_study_material_drive_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineCertificateReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_year', models.PositiveIntegerField(db_index=True, default=classroom.certifications.models.current_year, verbose_name='año')),
                ('district', models.CharField(db_index=True, max_length=120, verbose_name='distrito / regional')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='cantidad certificada online')),
                ('image', models.ImageField(blank=True, null=True, upload_to='certifications/online_reports/', verbose_name='imagen')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_certificate_reports', to='courses.course', verbose_name='curso')),
            ],
            options={
                'verbose_name': 'Reporte de Certificado Online',
                'verbose_name_plural': 'Reportes de Certificados Online',
                'ordering': ('-issued_year', 'district'),
                'constraints': [models.UniqueConstraint(fields=('course', 'issued_year', 'district'), name='unique_online_certificate_report')],
            },
        ),
    ]
