# Generated by Django 5.1.2 on 2026-05-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0010_onlinecertificatereport'),
        ('courses', '0013_course_study_material_drive_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onlinecertificatereport',
            options={'ordering': ('-issued_year', 'course'), 'verbose_name': 'Reporte de Certificado Online', 'verbose_name_plural': 'Reportes de Certificados Online'},
        ),
        migrations.RemoveConstraint(
            model_name='onlinecertificatereport',
            name='unique_online_certificate_report',
        ),
        migrations.RemoveField(
            model_name='onlinecertificatereport',
            name='district',
        ),
        migrations.RemoveField(
            model_name='onlinecertificatereport',
            name='quantity',
        ),
        migrations.AddField(
            model_name='onlinecertificatereport',
            name='districts_list',
            field=models.TextField(blank=True, default=None, help_text='Lista de distritos separados por comas: 01, 05, 06, 07, 15, 11, 13, 16', null=True, verbose_name='distritos/regionales'),
        ),
        migrations.AddField(
            model_name='onlinecertificatereport',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='cantidad total de certificados online'),
        ),
        migrations.AddConstraint(
            model_name='onlinecertificatereport',
            constraint=models.UniqueConstraint(fields=('course', 'issued_year'), name='unique_online_certificate_report'),
        ),
    ]
