# Generated by Django 5.1.2 on 2024-10-19 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_estatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nombre',
            new_name='Categoria',
        ),
    ]
