# Generated by Django 5.1.2 on 2024-10-19 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_nombre_categoria_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='Categoria',
            new_name='nombre',
        ),
    ]
