# Generated by Django 5.1.2 on 2025-10-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdefinition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='form_images/'),
        ),
    ]
