# Generated by Django 5.1.2 on 2025-11-06 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='CategoriaMenu',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
