# Generated by Django 6.0 on 2026-04-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='scholarship_country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='invitation',
            name='scholarship_district',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='scholarship_province',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invitation',
            name='scholarship_regional',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
