# Generated by Django 5.1.2 on 2025-01-26 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImplementationEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_center', models.CharField(max_length=255)),
                ('responsables', models.TextField()),
                ('dates', models.DateField()),
                ('topics', models.TextField()),
                ('objective', models.TextField()),
                ('methodology', models.TextField()),
                ('highlights', models.TextField(blank=True, null=True)),
                ('incidences', models.TextField(blank=True, null=True)),
                ('impacted_females', models.PositiveIntegerField(default=0)),
                ('impacted_males', models.PositiveIntegerField(default=0)),
                ('impacted_ages', models.CharField(blank=True, max_length=255, null=True)),
                ('school_impact', models.TextField(blank=True, null=True)),
                ('family_impact', models.TextField(blank=True, null=True)),
                ('social_impact', models.TextField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='evidences/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
