# Generated by Django 5.1.3 on 2024-11-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images/', verbose_name='Imagen de Portada'),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='Miniatura'),
        ),
        migrations.AddField(
            model_name='post',
            name='use_thumbnail_as_cover',
            field=models.BooleanField(default=False, verbose_name='Usar Miniatura como Portada'),
        ),
    ]
