# Generated by Django 5.1.2 on 2024-10-18 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_poststatus_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='status',
            new_name='estatus',
        ),
    ]
