# Generated by Django 5.1.3 on 2024-11-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_cover_image_post_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/cover_images/', verbose_name='Imagen de Portada'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/thumbnails/', verbose_name='Miniatura'),
        ),
    ]
