# Generated by Django 5.1.2 on 2024-10-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_status_post_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='estatus',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='publicado', max_length=100),
        ),
    ]
