# Generated by Django 5.1.2 on 2024-11-17 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_cover_image_alter_post_thumbnail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='blogCategory',
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='blogPost',
        ),
    ]
