# Generated by Django 5.1.2 on 2025-06-23 02:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_category_blogcategory_rename_post_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Biografía'),
        ),
    ]
