# Generated by Django 5.1.2 on 2025-11-05 02:36

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Removed dependency on a specific 'page' migration which was not present in the repo
        # (was: ('page', '0018_remove_pagecontent_category_and_more')).
        # If your 'page' app provides models referenced below, add a dependency to a valid
        # migration for that app (for example: ('page', '0001_initial')) or restore the
        # missing migration file. For now we keep only the auth user dependency.
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría de Contenido',
                'verbose_name_plural': 'Categorías de Contenido',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=220, null=True, unique=True)),
                ('content', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='gallery/cover_images/', verbose_name='Imagen de Portada')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='gallery/thumbnails/', verbose_name='Miniatura')),
                ('use_thumbnail_as_cover', models.BooleanField(default=False, verbose_name='Usar Miniatura como Portada')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='Etiquetas (separadas por comas)')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('archived', 'Archivado')], default='draft', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='contents.contentcategory', verbose_name='Categoría')),
                # The original migration referenced a separate 'page' app for Page/PageSection
                # which is not present in this repository. The current model defines
                # `section` as a CharField (not a FK), so we create a matching field here.
                ('section', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sections')),
            ],
            options={
                'verbose_name': 'Contenido',
                'verbose_name_plural': 'Contenidos',
                'ordering': ['-created_at'],
            },
        ),
    ]
