# Generated by Django 5.1.2 on 2025-11-06 01:05

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        # RemoveField for 'page' was removed because the initial migration no longer
        # defines a 'page' field (project uses a CharField for `section` instead of
        # a ForeignKey to a separate 'page' app). Keeping the RemoveField would
        # raise KeyError during migration graph construction.
        migrations.AlterField(
            model_name='contentpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='contents.contentcategory', verbose_name='PostCategory'),
        ),
        migrations.AlterField(
            model_name='contentpost',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='contentpost',
            name='section',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sections'),
        ),
        migrations.AlterField(
            model_name='contentpost',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Título'),
        ),
    ]
