# Generated by Django 5.1.2 on 2025-11-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_remove_contentpost_page_alter_contentpost_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpost',
            name='section',
            field=models.IntegerField(blank=True, max_length=2, null=True, verbose_name='Sections'),
        ),
    ]
