# Generated by Django 5.1.2 on 2025-11-07 06:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_alter_contentpost_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpost',
            name='section',
            field=models.IntegerField(blank=True, max_length=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
