# Generated by Django 5.1.2 on 2025-11-12 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_alter_contentpost_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpost',
            name='section',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
