# Generated by Django 5.1.2 on 2025-12-26 12:40

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_alter_contentpost_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpost',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Contenido'),
        ),
    ]
