# Generated by Django 5.1.2 on 2026-01-06 04:57

from django.db import migrations

def copy_old_addresses_forward(apps, schema_editor):
    OldAddress = apps.get_model('authentication', 'Address')
    NewAddress = apps.get_model('address', 'Address')

    db_alias = schema_editor.connection.alias
    for old in OldAddress.objects.using(db_alias).all():
        NewAddress.objects.using(db_alias).update_or_create(
            user_id=old.user_id,
            address_type=old.address_type,
            defaults={
                'street': old.street,
                'neighborhood': old.neighborhood,
                'city': old.city,
                'state': old.state,
                'zip_code': old.zip_code,
            },
        )

def delete_new_addresses_backward(apps, schema_editor):
    NewAddress = apps.get_model('address', 'Address')
    db_alias = schema_editor.connection.alias
    NewAddress.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('authentication', '0023_alter_biography_biography_alter_directives_biografia'),
    ]

    operations = [
        migrations.RunPython(copy_old_addresses_forward, delete_new_addresses_backward)
    ]
