# Generated by Django 5.1.2 on 2025-06-23 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_address_city_alter_address_neighborhood_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffs',
            name='nivel_acceso',
        ),
    ]
