# Generated by Django 5.1.2 on 2024-10-26 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_profile_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profession',
            new_name='profesion',
        ),
        migrations.AddField(
            model_name='profile',
            name='puesto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
