# Generated by Django 5.1.2 on 2025-06-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_staffs_biografia_directives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directives',
            name='biografia',
            field=models.TextField(verbose_name='Contenido'),
        ),
    ]
