# Generated by Django 5.1.2 on 2025-06-23 02:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_staffs_biografia_directives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directives',
            name='biografia',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
    ]
