# Generated by Django 5.1.2 on 2024-10-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='excerpt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
