# Generated by Django 5.1.2 on 2025-06-23 02:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_directives_biografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directives',
            name='biografia',
            field=ckeditor.fields.RichTextField(verbose_name='Biografia'),
        ),
    ]
