# Generated by Django 5.1.2 on 2025-06-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_directives_biografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directives',
            name='biografia',
            field=models.TextField(verbose_name='Biografia'),
        ),
    ]
