# Generated by Django 5.1.2 on 2024-11-17 18:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_biography_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='biography',
            field=ckeditor.fields.RichTextField(verbose_name='Biografia'),
        ),
    ]
