# Generated by Django 5.1.2 on 2024-11-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_biography_biography'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='puesto',
            new_name='roll',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='calle_y_casa',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sector_o_barrio',
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle_y_casa', models.CharField(blank=True, max_length=120, null=True)),
                ('sector_o_barrio', models.CharField(blank=True, max_length=120, null=True)),
                ('municipio', models.CharField(blank=True, max_length=120, null=True)),
                ('provincia', models.CharField(blank=True, max_length=120, null=True)),
                ('codigo_postal', models.IntegerField(blank=True, null=True)),
                ('perfiles', models.ManyToManyField(related_name='direcciones', to='authentication.profile')),
            ],
        ),
    ]
