# Generated by Django 5.1.2 on 2025-06-23 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_directives_biografia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='old_cart',
        ),
    ]
