# Generated by Django 5.1.2 on 2024-11-27 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_rename_puesto_profile_roll_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='perfiles',
        ),
        migrations.AddField(
            model_name='profile',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Direcciones', to='authentication.direccion'),
        ),
    ]
