# Generated by Django 5.1.2 on 2025-06-23 17:28

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_profiles_old_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biografias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Biografia')),
            ],
        ),
        migrations.RenameField(
            model_name='directives',
            old_name='roll',
            new_name='role',
        ),
        migrations.AlterField(
            model_name='directives',
            name='biografia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.biografias'),
        ),
    ]
