# Generated by Django 5.1.2 on 2024-11-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_direccion_perfiles_profile_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biography',
            name='excerpt',
        ),
    ]
