# Generated by Django 5.1.2 on 2025-06-23 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_biografias_rename_roll_directives_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directives',
            old_name='role',
            new_name='roll',
        ),
    ]
