# Generated by Django 5.1.2 on 2025-06-23 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_rename_role_directives_roll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directives',
            old_name='roll',
            new_name='role',
        ),
    ]
