# Generated by Django 5.1.2 on 2024-12-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_profile_old_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imagen',
            field=models.ImageField(default='profiles/default.jpg', upload_to='profiles/'),
        ),
    ]
