# Generated by Django 5.1.2 on 2025-06-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_biografias_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directives',
            old_name='Profiles',
            new_name='profiles',
        ),
        migrations.AlterField(
            model_name='directives',
            name='biografia',
            field=models.TextField(verbose_name='Biografia'),
        ),
    ]
