# Generated by Django 5.1.2 on 2025-06-24 01:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_biografias_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directives',
            old_name='Profiles',
            new_name='profiles',
        ),
        migrations.AlterField(
            model_name='directives',
            name='biografia',
            field=ckeditor.fields.RichTextField(verbose_name='Biografia'),
        ),
    ]
