# Generated by Django 5.1.2 on 2025-06-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_rename_profiles_directives_profiles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directives',
            name='biografia',
            field=models.TextField(blank=True, null=True, verbose_name='Biografia'),
        ),
    ]
