# Generated by Django 5.1.2 on 2025-06-24 01:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_rename_profiles_directives_profiles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directives',
            name='biografia',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Biografia'),
        ),
    ]
