# Generated by Django 5.1.2 on 2025-07-15 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_directives_biografia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Biografias',
        ),
    ]
