# Generated by Django 5.1.2 on 2025-07-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_delete_biografias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='students',
            name='degree',
        ),
        migrations.AddField(
            model_name='students',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='cedula',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='students',
            name='distrito_educativo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='genero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='institucion_laboral',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='pendiente',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='students',
            name='regional',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
