# Generated by Django 5.1.2 on 2025-06-03 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_studentprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProgress',
        ),
    ]
