# Generated by Django 5.1.2 on 2025-07-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_remove_students_certifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('laboral', 'Laboral'), ('residencial', 'Residencial'), ('otro', 'Otro')], default='residencial', max_length=20),
        ),
        migrations.AddField(
            model_name='students',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='genero',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10, null=True),
        ),
    ]
