# Generated by Django 5.1.2 on 2025-07-26 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_address_address_type_students_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='address',
        ),
    ]
