# Generated by Django 5.1.2 on 2025-08-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_remove_students_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='old_cart',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
