# Generated by Django 5.1.2 on 2025-10-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_profiles_old_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='certificados/')),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='certification',
            field=models.FileField(blank=True, null=True, upload_to='Certification/'),
        ),
    ]
