# Generated by Django 5.1.2 on 2025-11-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_certification_students_certification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directives',
            name='role',
        ),
        migrations.AddField(
            model_name='directives',
            name='cargo',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='directives',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directives',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='directiva_fotos/'),
        ),
        migrations.AddField(
            model_name='directives',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directives',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='por_distrito',
            field=models.BooleanField(default=False),
        ),
    ]
