# Generated by Django 5.1.2 on 2025-11-15 05:16

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_remove_directives_role_directives_cargo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Dirección', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='directives',
            options={'verbose_name': 'Directivo', 'verbose_name_plural': 'Directivos'},
        ),
        migrations.AlterModelOptions(
            name='staffs',
            options={'verbose_name': 'Personal', 'verbose_name_plural': 'Personal'},
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='Profiles',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='directives',
            old_name='profiles',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='staffs',
            old_name='Profiles',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customers',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='authentication.address'),
        ),
        migrations.AlterField(
            model_name='directives',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directives', to='authentication.address'),
        ),
        migrations.AlterField(
            model_name='directives',
            name='biografia',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Biografía'),
        ),
        migrations.AlterField(
            model_name='directives',
            name='cargo',
            field=models.CharField(max_length=150, null=True, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='directives',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='directives',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='directiva_fotos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='directives',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='directives',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to='authentication.address'),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('user', 'address_type')},
        ),
    ]
