# Generated by Django 5.1.2 on 2025-12-26 06:52

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_alter_address_options_alter_customers_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='biography',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='directives',
            name='biografia',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Biografía'),
        ),
    ]
