# Generated by Django 5.1.2 on 2026-01-06 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_alter_address_user'),
        ('authentication', '0023_alter_biography_biography_alter_directives_biografia'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.AlterField(
            model_name='customers',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='address.address'),
        ),
        migrations.AlterField(
            model_name='directives',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directives', to='address.address'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to='address.address'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Direcciones', to='address.address'),
        ),
    ]
