# Generated by Django 5.1.2 on 2026-01-06 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_alter_address_unique_together_remove_address_user_and_more'),
        ('enrollments', '0005_alter_becaapplication_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
