# Generated by Django 5.1.2 on 2026-01-14 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
