<<<<<<< HEAD
# Generated by Django 5.1.2 on 2026-01-19 05:20
=======
# Generated by Django 5.1.2 on 2026-01-19 17:23
>>>>>>> dev

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_delete_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'authentication_address',
                'managed': False,
            },
        ),
    ]
