# Generated by Django 6.0 on 2026-04-27 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='curriculum_vitae',
            field=models.FileField(blank=True, null=True, upload_to='profiles/cv/'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='estado_academico',
            field=models.CharField(blank=True, choices=[('graduado', 'Graduado'), ('no_graduado', 'No graduado')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='nivel_academico',
            field=models.CharField(blank=True, choices=[('basico', 'Estudio Basico'), ('secundario', 'Estudio Secundario'), ('tecnico', 'Estudio Tecnico'), ('universitario', 'Estudio Universitario')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='AcademicEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('certificacion', 'Certificacion'), ('diploma', 'Diploma'), ('licenciatura', 'Licenciatura')], max_length=20)),
                ('file', models.FileField(upload_to='profiles/evidencias_academicas/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_evidences', to='authentication.profiles')),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
    ]
