# Generated by Django 6.0 on 2026-04-27 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0029_profiles_curriculum_vitae_profiles_estado_academico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipStudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('republica_dominicana', 'Republica Dominicana'), ('estados_unidos', 'Estados Unidos'), ('canada', 'Canada'), ('mexico', 'Mexico'), ('colombia', 'Colombia'), ('venezuela', 'Venezuela'), ('argentina', 'Argentina'), ('chile', 'Chile'), ('peru', 'Peru'), ('ecuador', 'Ecuador')], max_length=50)),
                ('district', models.PositiveIntegerField()),
                ('regional', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
