# Generated by Django 5.1.2 on 2026-01-11 15:18

import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0009_alter_quicktestresult_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_year', models.PositiveIntegerField(db_index=True, default=home.models.current_year, verbose_name='año')),
                ('district', models.CharField(db_index=True, max_length=120, verbose_name='distrito / regional')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='cantidad presencial')),
                ('image', models.ImageField(blank=True, null=True, upload_to='certifications/report_activities/', verbose_name='imagen')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_activities', to='courses.course', verbose_name='curso')),
            ],
            options={
                'verbose_name': 'Actividad de Reporte',
                'verbose_name_plural': 'Actividades de Reportes',
                'ordering': ('-issued_year', 'district'),
                'constraints': [models.UniqueConstraint(fields=('course', 'issued_year', 'district'), name='unique_reportactivity_course_year_district')],
            },
        ),
    ]
