# Generated by Django 5.1.2 on 2026-01-16 03:05

import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_quicktestresult_unique_together_and_more'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='reportactivity',
            name='unique_reportactivity_course_year_district',
        ),
        migrations.AddField(
            model_name='reportactivity',
            name='categories',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='report_activities', to='home.reportcategories', verbose_name='categoría'),
        ),
        migrations.AddConstraint(
            model_name='reportactivity',
            constraint=models.UniqueConstraint(fields=('course', 'issued_year', 'district', 'categories'), name='unique_reportactivity_course_year_district'),
        ),
    ]
