# Generated by Django 5.1.2 on 2026-01-16 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_reportcategories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportcategories',
            old_name='Name',
            new_name='name',
        ),
    ]
