# Generated by Django 5.1.2 on 2025-10-30 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('name', models.SlugField(help_text='Nombre interno del campo (sin espacios ni caracteres especiales)')),
                ('field_type', models.CharField(choices=[('char', 'Campo de texto'), ('email', 'Correo electrónico'), ('integer', 'Número entero'), ('text', 'Área de texto'), ('boolean', 'Casilla de verificación'), ('select', 'Selección')], max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('choices', models.TextField(blank=True, help_text='Solo para campos tipo selección. Separar opciones por coma.', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='formbuilder.formdefinition')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
