# Generated by Django 5.1.2 on 2025-11-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0003_completedform'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedform',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completedform',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
