# Generated by Django 5.1.2 on 2025-11-15 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('authentication', '0022_alter_address_options_alter_customers_options_and_more'),
        ('formbuilder', '0004_completedform_descripcion_completedform_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedform',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Dirección del facilitador', null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address'),
        ),
        migrations.AddField(
            model_name='completedform',
            name='distrito',
            field=models.CharField(blank=True, help_text='Distrito del facilitador', max_length=100, null=True),
        ),
    ]
