# Generated by Django 5.1.2 on 2025-12-26 06:44

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0007_anexos_to_multiple_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdefinition',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('char', 'Campo de texto'), ('email', 'Correo electrónico'), ('integer', 'Número entero'), ('text', 'Área de texto'), ('boolean', 'Casilla de verificación'), ('select', 'Selección'), ('files', 'Anexos (múltiples archivos)')], max_length=20),
        ),
    ]
