# Generated by Django 5.1.2 on 2025-12-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0008_alter_formdefinition_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdefinition',
            name='image_left',
            field=models.ImageField(blank=True, null=True, upload_to='form_images/'),
        ),
        migrations.AddField(
            model_name='formdefinition',
            name='image_right',
            field=models.ImageField(blank=True, null=True, upload_to='form_images/'),
        ),
    ]
