# Generated by Django 5.1.2 on 2026-01-06 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_alter_address_user'),
        ('formbuilder', '0009_formdefinition_image_left_formdefinition_image_right'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedform',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Dirección del facilitador', null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address'),
        ),
    ]
