# Generated by Django 5.1.2 on 2026-01-14 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_alter_address_user'),
        ('formbuilder', '0010_alter_completedform_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedform',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address'),
        ),
    ]
