# Generated by Django 5.1.2 on 2026-02-14 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0012_formsharelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedform',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formbuilder.formdefinition'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='name',
            field=models.SlugField(blank=True, help_text='Nombre interno del campo (sin espacios ni caracteres especiales)'),
        ),
    ]
