# Generated by Codex on 2026-02-14

from django.db import migrations


def forwards(apps, schema_editor):
    FormDefinition = apps.get_model("formbuilder", "FormDefinition")
    CompletedForm = apps.get_model("formbuilder", "CompletedForm")

    name_to_id = {
        f.name: f.id for f in FormDefinition.objects.all().only("id", "name")
    }

    for cf in CompletedForm.objects.filter(form__isnull=True).only("id", "form_name"):
        form_id = name_to_id.get(cf.form_name)
        if form_id:
            CompletedForm.objects.filter(id=cf.id).update(form_id=form_id)


def backwards(apps, schema_editor):
    CompletedForm = apps.get_model("formbuilder", "CompletedForm")
    CompletedForm.objects.filter(form__isnull=False).update(form_id=None)


class Migration(migrations.Migration):
    dependencies = [
        ("formbuilder", "0013_completedform_form_alter_formfield_name"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
