# Generated by Django 5.1.2 on 2024-10-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='#', max_length=100)),
                ('mision', models.TextField()),
                ('enlace_inicio', models.URLField(default='#')),
                ('enlace_quienes_somos', models.URLField(default='#')),
                ('enlace_contacto', models.URLField(default='#')),
                ('enlace_galeria', models.URLField(default='#')),
                ('email_contacto', models.EmailField(max_length=254)),
                ('telefono_contacto', models.CharField(max_length=15)),
                ('derechos_autor', models.CharField(default='© 2024 Living Better Community Center. Todos los derechos reservados.', max_length=255)),
            ],
        ),
    ]
