# Generated by Django 5.1.2 on 2024-10-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_pageimg_imagenpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenpage',
            old_name='habilidad',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='imagenpage',
            name='imagen',
            field=models.ImageField(upload_to='pageImg/'),
        ),
    ]
