# Generated by Django 5.1.2 on 2024-10-29 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_rename_habilidad_imagenpage_nombre_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageImg',
            new_name='CategoryImages',
        ),
        migrations.RemoveField(
            model_name='imagenpage',
            name='nombre',
        ),
        migrations.AddField(
            model_name='imagenpage',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='CategoryImages', to='page.categoryimages'),
        ),
    ]
