# Generated by Django 5.1.2 on 2024-10-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_rename_pageimg_categoryimages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenpage',
            name='details',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
