# Generated by Django 5.1.2 on 2024-11-17 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_imagenpage_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pagecontent',
            name='column',
        ),
        migrations.AddField(
            model_name='column',
            name='num',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('pending', 'Pending')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='pageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Categoria de la pagina')),
                ('column', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='page.column')),
            ],
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='catgory_page', to='page.pagecategory'),
        ),
    ]
