# Generated by Django 5.1.2 on 2024-11-17 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_remove_column_name_remove_pagecontent_column_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagecategory',
            name='column',
        ),
        migrations.AddField(
            model_name='column',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='page.pagecategory'),
        ),
    ]
