# Generated by Django 5.1.2 on 2024-11-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_remove_pagecategory_column_column_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecategory',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pagecategory',
            name='description',
            field=models.TextField(blank=True, help_text='Categoría de la página'),
        ),
    ]
