# Generated by Django 5.1.2 on 2024-11-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_pagecategory_slug_alter_pagecategory_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagecontent',
            name='tab',
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='page/cover_images/', verbose_name='Imagen de Portada'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='page/thumbnails/', verbose_name='Miniatura'),
        ),
    ]
