# Generated by Django 5.1.2 on 2024-11-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_remove_pagecontent_tab_pagecontent_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagecontent',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images/', verbose_name='Imagen de Portada'),
        ),
    ]
