# Generated by Django 5.1.2 on 2024-11-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_remove_pagecontent_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images/'),
        ),
    ]
