# Generated by Django 5.1.2 on 2024-11-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_alter_pagecontent_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='pageContentImages/'),
        ),
    ]
