# Generated by Django 5.1.2 on 2024-11-21 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0015_alter_pagecontent_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='page.pagecategory'),
        ),
        migrations.CreateModel(
            name='PagePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(blank=True, default=None)),
                ('column', models.IntegerField(blank=True, default=None)),
                ('description', models.TextField(blank=True, help_text='Descripción opcional de la columna')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='page.pagecategory')),
            ],
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='position',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='content_positions', to='page.pageposition'),
        ),
        migrations.DeleteModel(
            name='Column',
        ),
    ]
