# Generated by Django 5.1.2 on 2024-11-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0016_alter_pagecontent_category_pageposition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='carouselPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='pageImg/')),
                ('details', models.CharField(blank=True, default=None, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='imagenpage',
            name='category',
        ),
        migrations.DeleteModel(
            name='CategoryImages',
        ),
        migrations.DeleteModel(
            name='ImagenPage',
        ),
    ]
