# Generated by Django 5.1.2 on 2025-11-04 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0017_carouselpage_remove_imagenpage_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagecontent',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pageposition',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pagecontent',
            name='author',
        ),
        migrations.RemoveField(
            model_name='pagecontent',
            name='position',
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Page Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('show_in_navbar', models.BooleanField(default=True, help_text='Display this page in the main navigation menu.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, help_text='Optional parent page for nested navigation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subpages', to='page.page')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Section Name')),
                ('row', models.PositiveIntegerField(default=1)),
                ('column', models.PositiveIntegerField(default=1)),
                ('zone', models.CharField(blank=True, help_text="Optional visual identifier (e.g., 'header', 'sidebar').", max_length=100, verbose_name='Zone')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='page.page')),
            ],
            options={
                'verbose_name': 'Page Section',
                'verbose_name_plural': 'Page Sections',
                'ordering': ['page', 'row', 'column'],
            },
        ),
        migrations.DeleteModel(
            name='pageCategory',
        ),
        migrations.DeleteModel(
            name='PageContent',
        ),
        migrations.DeleteModel(
            name='PagePosition',
        ),
    ]
