# Generated by Django 5.1.2 on 2025-10-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Campo',
                'verbose_name_plural': 'Campos',
            },
        ),
        migrations.CreateModel(
            name='ReportAccountMinerd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=250, null=True)),
                ('centro_educativo', models.CharField(max_length=200)),
                ('responsabilidades', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('temas_impartidos', models.TextField(blank=True, null=True)),
                ('objetivo_razon_motivo', models.TextField(blank=True, null=True)),
                ('regional', models.CharField(max_length=150)),
                ('documentos', models.FileField(blank=True, null=True, upload_to='reportes_minerd/')),
                ('campos', models.ManyToManyField(related_name='reportes', to='minerd.campo')),
            ],
            options={
                'verbose_name': 'Reporte MINERD',
                'verbose_name_plural': 'Reportes MINERD',
                'ordering': ['-fecha'],
            },
        ),
    ]
