# Generated by Django 5.1.2 on 2025-10-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minerd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportaccountminerd',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
