# Generated by Django 5.1.2 on 2025-10-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minerd', '0002_alter_reportaccountminerd_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportaccountminerd',
            name='campos',
            field=models.ManyToManyField(blank=True, related_name='reportes', to='minerd.campo'),
        ),
        migrations.AlterField(
            model_name='reportaccountminerd',
            name='centro_educativo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reportaccountminerd',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportaccountminerd',
            name='regional',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
